#!/usr/bin/env python3
"""
High-frequency classical lemma seeds (WORDS / school-lexicon style).

These headwords are forced into the train split for morph open-set so that
productive inflection (aquarum, manibus, duco…) has a donor lemma.
Does not use free generation — fixed FSOT-friendly curriculum list.

Also provides English gloss synonym clusters for sense reinforcement.
"""
from __future__ import annotations

from typing import Dict, List, Set, Tuple

# (lang, form, english_gloss)
CORE_SEEDS: List[Tuple[str, str, str]] = [
    # Latin high-frequency
    ("la", "aqua", "water"),
    ("la", "manus", "hand"),
    ("la", "pes", "foot"),
    ("la", "caput", "head"),
    ("la", "corpus", "body"),
    ("la", "oculus", "eye"),
    ("la", "os", "mouth"),
    ("la", "dens", "tooth"),
    ("la", "cor", "heart"),
    ("la", "vox", "voice"),
    ("la", "lingua", "language"),
    ("la", "verbum", "word"),
    ("la", "nomen", "name"),
    ("la", "rex", "king"),
    ("la", "regina", "queen"),
    ("la", "homo", "man"),
    ("la", "mulier", "woman"),
    ("la", "puer", "boy"),
    ("la", "pater", "father"),
    ("la", "mater", "mother"),
    ("la", "filius", "son"),
    ("la", "filia", "daughter"),
    ("la", "deus", "god"),
    ("la", "dea", "goddess"),
    ("la", "dominus", "lord"),
    ("la", "servus", "slave"),
    ("la", "bellum", "war"),
    ("la", "pax", "peace"),
    ("la", "urbs", "city"),
    ("la", "casa", "house"),
    ("la", "via", "road"),
    ("la", "mare", "sea"),
    ("la", "terra", "earth"),
    ("la", "caelum", "sky"),
    ("la", "sol", "sun"),
    ("la", "luna", "moon"),
    ("la", "nox", "night"),
    ("la", "dies", "day"),
    ("la", "annus", "year"),
    ("la", "tempus", "time"),
    ("la", "locus", "place"),
    ("la", "res", "thing"),
    ("la", "causa", "cause"),
    ("la", "lex", "law"),
    ("la", "ius", "law"),
    ("la", "fides", "faith"),
    ("la", "amor", "love"),
    ("la", "mors", "death"),
    ("la", "vita", "life"),
    ("la", "sanguis", "blood"),
    ("la", "ignis", "fire"),
    ("la", "aqua", "water"),
    ("la", "ventus", "wind"),
    ("la", "flumen", "river"),
    ("la", "mons", "mountain"),
    ("la", "silva", "forest"),
    ("la", "ager", "field"),
    ("la", "frater", "brother"),
    ("la", "soror", "sister"),
    ("la", "amicus", "friend"),
    ("la", "hostis", "enemy"),
    ("la", "populus", "people"),
    ("la", "gens", "clan"),
    ("la", "duco", "lead"),
    ("la", "facio", "make"),
    ("la", "ago", "do"),
    ("la", "fero", "carry"),
    ("la", "sum", "be"),
    ("la", "habeo", "have"),
    ("la", "video", "see"),
    ("la", "audio", "hear"),
    ("la", "dico", "say"),
    ("la", "scribo", "write"),
    ("la", "lego", "read"),
    ("la", "venio", "come"),
    ("la", "eo", "go"),
    ("la", "do", "give"),
    ("la", "capio", "take"),
    ("la", "pono", "put"),
    ("la", "mitto", "send"),
    ("la", "sto", "stand"),
    ("la", "sedeo", "sit"),
    ("la", "curro", "run"),
    ("la", "vivo", "live"),
    ("la", "morior", "die"),
    ("la", "amo", "love"),
    ("la", "timeo", "fear"),
    ("la", "scio", "know"),
    ("la", "credo", "believe"),
    ("la", "possum", "be able"),
    ("la", "volo", "want"),
    ("la", "nolo", "not want"),
    ("la", "magnus", "great"),
    ("la", "parvus", "small"),
    ("la", "bonus", "good"),
    ("la", "malus", "bad"),
    ("la", "novus", "new"),
    ("la", "vetus", "old"),
    ("la", "longus", "long"),
    ("la", "brevis", "short"),
    ("la", "altus", "high"),
    ("la", "multus", "many"),
    ("la", "unus", "one"),
    ("la", "duo", "two"),
    ("la", "tres", "three"),
    ("la", "primus", "first"),
    ("la", "secundus", "second"),
    ("la", "totus", "whole"),
    ("la", "omnis", "all"),
    ("la", "nullus", "none"),
    ("la", "alius", "other"),
    ("la", "idem", "same"),
    ("la", "hic", "this"),
    ("la", "ille", "that"),
    ("la", "qui", "who"),
    ("la", "quid", "what"),
    ("la", "et", "and"),
    ("la", "sed", "but"),
    ("la", "aut", "or"),
    ("la", "non", "not"),
    ("la", "in", "in"),
    ("la", "ad", "to"),
    ("la", "ab", "from"),
    ("la", "cum", "with"),
    ("la", "sine", "without"),
    ("la", "pro", "for"),
    ("la", "per", "through"),
    ("la", "de", "about"),
    ("la", "ex", "out of"),
    ("la", "sub", "under"),
    ("la", "super", "above"),
    # Greek high-frequency
    ("grc", "ὕδωρ", "water"),
    ("grc", "ὕδωρ", "water"),
    ("grc", "χειρ", "hand"),
    ("grc", "χείρ", "hand"),
    ("grc", "πούς", "foot"),
    ("grc", "κεφαλή", "head"),
    ("grc", "σῶμα", "body"),
    ("grc", "ὀφθαλμός", "eye"),
    ("grc", "στόμα", "mouth"),
    ("grc", "καρδία", "heart"),
    ("grc", "φωνή", "voice"),
    ("grc", "λόγος", "word"),
    ("grc", "ὄνομα", "name"),
    ("grc", "γλῶσσα", "tongue"),
    ("grc", "βασιλεύς", "king"),
    ("grc", "ἀνήρ", "man"),
    ("grc", "γυνή", "woman"),
    ("grc", "παῖς", "child"),
    ("grc", "πατήρ", "father"),
    ("grc", "μήτηρ", "mother"),
    ("grc", "υἱός", "son"),
    ("grc", "θυγάτηρ", "daughter"),
    ("grc", "θεός", "god"),
    ("grc", "θεά", "goddess"),
    ("grc", "πόλις", "city"),
    ("grc", "οἶκος", "house"),
    ("grc", "ὁδός", "road"),
    ("grc", "θάλασσα", "sea"),
    ("grc", "γῆ", "earth"),
    ("grc", "οὐρανός", "sky"),
    ("grc", "ἥλιος", "sun"),
    ("grc", "σελήνη", "moon"),
    ("grc", "νύξ", "night"),
    ("grc", "ἡμέρα", "day"),
    ("grc", "ἔτος", "year"),
    ("grc", "χρόνος", "time"),
    ("grc", "τόπος", "place"),
    ("grc", "πρᾶγμα", "thing"),
    ("grc", "νόμος", "law"),
    ("grc", "δίκη", "justice"),
    ("grc", "ἔρως", "love"),
    ("grc", "θάνατος", "death"),
    ("grc", "βίος", "life"),
    ("grc", "αἷμα", "blood"),
    ("grc", "πῦρ", "fire"),
    ("grc", "ἀήρ", "air"),
    ("grc", "ποταμός", "river"),
    ("grc", "ὄρος", "mountain"),
    ("grc", "ὕλη", "forest"),
    ("grc", "ἀγρός", "field"),
    ("grc", "ἀδελφός", "brother"),
    ("grc", "ἀδελφή", "sister"),
    ("grc", "φίλος", "friend"),
    ("grc", "ἐχθρός", "enemy"),
    ("grc", "λαός", "people"),
    ("grc", "ἔθνος", "nation"),
    ("grc", "ἄγω", "lead"),
    ("grc", "ποιέω", "make"),
    ("grc", "εἰμί", "be"),
    ("grc", "ἔχω", "have"),
    ("grc", "ὁράω", "see"),
    ("grc", "ἀκούω", "hear"),
    ("grc", "λέγω", "say"),
    ("grc", "γράφω", "write"),
    ("grc", "ἔρχομαι", "come"),
    ("grc", "βαίνω", "go"),
    ("grc", "δίδωμι", "give"),
    ("grc", "λαμβάνω", "take"),
    ("grc", "τίθημι", "put"),
    ("grc", "πέμπω", "send"),
    ("grc", "ἵστημι", "stand"),
    ("grc", "κάθημαι", "sit"),
    ("grc", "τρέχω", "run"),
    ("grc", "ζάω", "live"),
    ("grc", "θνῄσκω", "die"),
    ("grc", "φιλέω", "love"),
    ("grc", "φοβέω", "fear"),
    ("grc", "οἶδα", "know"),
    ("grc", "πιστεύω", "believe"),
    ("grc", "δύναμαι", "be able"),
    ("grc", "βούλομαι", "want"),
    ("grc", "μέγας", "great"),
    ("grc", "μικρός", "small"),
    ("grc", "ἀγαθός", "good"),
    ("grc", "κακός", "bad"),
    ("grc", "νέος", "new"),
    ("grc", "παλαιός", "old"),
    ("grc", "μακρός", "long"),
    ("grc", "βραχύς", "short"),
    ("grc", "πολύς", "many"),
    ("grc", "εἷς", "one"),
    ("grc", "δύο", "two"),
    ("grc", "τρεῖς", "three"),
    ("grc", "πρῶτος", "first"),
    ("grc", "πᾶς", "all"),
    ("grc", "οὐδείς", "none"),
    ("grc", "ἄλλος", "other"),
    ("grc", "αὐτός", "self"),
    ("grc", "οὗτος", "this"),
    ("grc", "ἐκεῖνος", "that"),
    ("grc", "τίς", "who"),
    ("grc", "τί", "what"),
    ("grc", "καί", "and"),
    ("grc", "ἀλλά", "but"),
    ("grc", "ἤ", "or"),
    ("grc", "οὐ", "not"),
    ("grc", "ἐν", "in"),
    ("grc", "εἰς", "into"),
    ("grc", "ἐκ", "from"),
    ("grc", "σύν", "with"),
    ("grc", "πρό", "before"),
    ("grc", "διά", "through"),
    ("grc", "κατά", "down"),
    ("grc", "μετά", "after"),
    ("grc", "περί", "around"),
    ("grc", "ὑπό", "under"),
    ("grc", "ὑπέρ", "over"),
    # Old English high-frequency
    ("ang", "wæter", "water"),
    ("ang", "hand", "hand"),
    ("ang", "fot", "foot"),
    ("ang", "heafod", "head"),
    ("ang", "lichama", "body"),
    ("ang", "eage", "eye"),
    ("ang", "muð", "mouth"),
    ("ang", "heorte", "heart"),
    ("ang", "stefn", "voice"),
    ("ang", "word", "word"),
    ("ang", "nama", "name"),
    ("ang", "tunge", "tongue"),
    ("ang", "cyning", "king"),
    ("ang", "cwen", "queen"),
    ("ang", "mann", "man"),
    ("ang", "wif", "woman"),
    ("ang", "cild", "child"),
    ("ang", "fæder", "father"),
    ("ang", "modor", "mother"),
    ("ang", "sunu", "son"),
    ("ang", "dohtor", "daughter"),
    ("ang", "god", "god"),
    ("ang", "dryhten", "lord"),
    ("ang", "þeow", "slave"),
    ("ang", "guþ", "war"),
    ("ang", "sibb", "peace"),
    ("ang", "burh", "city"),
    ("ang", "hus", "house"),
    ("ang", "weg", "way"),
    ("ang", "sæ", "sea"),
    ("ang", "eorþe", "earth"),
    ("ang", "heofon", "heaven"),
    ("ang", "sunne", "sun"),
    ("ang", "mona", "moon"),
    ("ang", "niht", "night"),
    ("ang", "dæg", "day"),
    ("ang", "gear", "year"),
    ("ang", "tid", "time"),
    ("ang", "stow", "place"),
    ("ang", "þing", "thing"),
    ("ang", "æ", "law"),
    ("ang", "lufu", "love"),
    ("ang", "deaþ", "death"),
    ("ang", "lif", "life"),
    ("ang", "blod", "blood"),
    ("ang", "fyr", "fire"),
    ("ang", "lyft", "air"),
    ("ang", "ea", "river"),
    ("ang", "beorg", "mountain"),
    ("ang", "wudu", "forest"),
    ("ang", "æcer", "field"),
    ("ang", "broþor", "brother"),
    ("ang", "sweostor", "sister"),
    ("ang", "freond", "friend"),
    ("ang", "feond", "enemy"),
    ("ang", "folc", "people"),
    ("ang", "cynn", "kin"),
    ("ang", "don", "do"),
    ("ang", "wesan", "be"),
    ("ang", "habban", "have"),
    ("ang", "seon", "see"),
    ("ang", "hieran", "hear"),
    ("ang", "cweþan", "say"),
    ("ang", "writan", "write"),
    ("ang", "rædan", "read"),
    ("ang", "cuman", "come"),
    ("ang", "gan", "go"),
    ("ang", "gifan", "give"),
    ("ang", "niman", "take"),
    ("ang", "settan", "set"),
    ("ang", "sendan", "send"),
    ("ang", "standan", "stand"),
    ("ang", "sittan", "sit"),
    ("ang", "iernan", "run"),
    ("ang", "libban", "live"),
    ("ang", "sweltan", "die"),
    ("ang", "lufian", "love"),
    ("ang", "ondrædan", "fear"),
    ("ang", "witan", "know"),
    ("ang", "gelyfan", "believe"),
    ("ang", "magan", "be able"),
    ("ang", "willan", "want"),
    ("ang", "micel", "great"),
    ("ang", "lytel", "small"),
    ("ang", "god", "good"),
    ("ang", "yfel", "evil"),
    ("ang", "niwe", "new"),
    ("ang", "eald", "old"),
    ("ang", "lang", "long"),
    ("ang", "scort", "short"),
    ("ang", "heah", "high"),
    ("ang", "manig", "many"),
    ("ang", "an", "one"),
    ("ang", "twa", "two"),
    ("ang", "þreo", "three"),
    ("ang", "forma", "first"),
    ("ang", "eall", "all"),
    ("ang", "nan", "none"),
    ("ang", "oþer", "other"),
    ("ang", "and", "and"),
    ("ang", "ac", "but"),
    ("ang", "oþþe", "or"),
    ("ang", "ne", "not"),
    ("ang", "in", "in"),
    ("ang", "to", "to"),
    ("ang", "fram", "from"),
    ("ang", "mid", "with"),
    ("ang", "butan", "without"),
    ("ang", "for", "for"),
    ("ang", "þurh", "through"),
    ("ang", "be", "about"),
    ("ang", "of", "of"),
    ("ang", "under", "under"),
    ("ang", "ofer", "over"),
]


def seed_records() -> List[dict]:
    import re

    out = []
    seen = set()
    for lang, form, gloss in CORE_SEEDS:
        key = f"{lang}|{form}"
        if key in seen:
            continue
        seen.add(key)
        mk = re.sub(r"[^a-z0-9]+", "_", gloss.lower()).strip("_")
        out.append(
            {
                "source_lang": lang,
                "source_word": form,
                "target_lang": "en",
                "target_word": gloss,
                "meaning_key": mk,
                "confidence": 0.99,
                "tier": "A",
                "source_title": "core_lemma_seeds",
                "is_name": False,
            }
        )
    return out


def seed_keys() -> Set[str]:
    return {f"{lang}|{form}" for lang, form, _ in CORE_SEEDS}


# English gloss clusters — mutually reinforcing open-set soft credit / sense vote
GLOSS_CLUSTERS: List[Set[str]] = [
    {"water", "aqua", "h2o", "stream", "river", "sea", "liquid"},
    {"hand", "palm", "manual", "fist"},
    {"foot", "feet", "pes", "step"},
    {"head", "caput", "chief", "top"},
    {"body", "corpus", "flesh"},
    {"eye", "see", "sight", "vision"},
    {"mouth", "oral", "speak"},
    {"heart", "cordial", "core"},
    {"voice", "sound", "vox", "call"},
    {"word", "speech", "verb", "logos", "language", "tongue"},
    {"name", "noun", "title"},
    {"king", "rex", "royal", "ruler", "monarch"},
    {"queen", "regina"},
    {"man", "human", "person", "male", "homo"},
    {"woman", "female", "wife", "lady"},
    {"child", "boy", "girl", "kid", "puer"},
    {"father", "dad", "pater"},
    {"mother", "mom", "mater"},
    {"son", "filius"},
    {"daughter", "filia"},
    {"god", "deity", "divine", "deus"},
    {"goddess", "dea"},
    {"lord", "master", "dominus"},
    {"slave", "servant", "servus"},
    {"war", "battle", "bellum", "fight"},
    {"peace", "pax"},
    {"city", "town", "urbs", "polis"},
    {"house", "home", "domus", "oikos"},
    {"road", "way", "path", "via"},
    {"sea", "ocean", "mare"},
    {"earth", "land", "ground", "terra", "soil"},
    {"sky", "heaven", "caelum"},
    {"sun", "solar"},
    {"moon", "lunar"},
    {"night", "nocturnal"},
    {"day", "daily"},
    {"year", "annual"},
    {"time", "season", "tempus"},
    {"place", "location", "locus", "site"},
    {"thing", "matter", "res", "affair"},
    {"cause", "reason", "case"},
    {"law", "right", "ius", "lex", "legal"},
    {"faith", "trust", "belief", "fides"},
    {"love", "amor", "desire"},
    {"death", "die", "dead", "mors"},
    {"life", "live", "vita", "bios"},
    {"blood", "sanguine"},
    {"fire", "flame", "burn"},
    {"wind", "air", "breath"},
    {"river", "stream", "flumen"},
    {"mountain", "mount", "hill"},
    {"forest", "wood", "woods", "silva"},
    {"field", "acre", "ager"},
    {"brother", "frater"},
    {"sister", "soror"},
    {"friend", "ally", "amicus"},
    {"enemy", "foe", "hostis"},
    {"people", "folk", "nation", "populus"},
    {"lead", "guide", "bring", "duco"},
    {"make", "do", "create", "facio", "act"},
    {"carry", "bear", "bring", "fero"},
    {"be", "exist", "am", "is", "are"},
    {"have", "hold", "own"},
    {"see", "look", "watch", "view"},
    {"hear", "listen"},
    {"say", "speak", "tell", "talk"},
    {"write", "inscribe"},
    {"read", "collect"},
    {"come", "arrive"},
    {"go", "walk", "move"},
    {"give", "grant"},
    {"take", "seize", "capture", "receive"},
    {"put", "place", "set"},
    {"send", "dispatch"},
    {"stand", "stay"},
    {"sit", "seat"},
    {"run", "race"},
    {"live", "dwell"},
    {"die", "perish"},
    {"fear", "afraid", "dread"},
    {"know", "knowledge", "understand"},
    {"believe", "trust"},
    {"want", "wish", "will"},
    {"great", "large", "big", "grand"},
    {"small", "little", "tiny"},
    {"good", "well", "fine"},
    {"bad", "evil", "wicked"},
    {"new", "fresh"},
    {"old", "ancient", "aged"},
    {"long", "lengthy"},
    {"short", "brief"},
    {"high", "tall", "deep"},
    {"many", "much", "numerous"},
    {"one", "single", "alone"},
    {"two", "pair"},
    {"three", "triple"},
    {"first", "primary"},
    {"second", "secondary"},
    {"all", "every", "whole", "entire"},
    {"none", "no", "nothing"},
    {"other", "another", "else"},
    {"same", "identical"},
    {"and", "also"},
    {"but", "however"},
    {"or", "either"},
    {"not", "no"},
]


def build_synonym_map() -> Dict[str, Set[str]]:
    m: Dict[str, Set[str]] = {}
    for cluster in GLOSS_CLUSTERS:
        for w in cluster:
            m[w] = set(cluster)
    return m


_SYN_MAP: Dict[str, Set[str]] | None = None


def synonyms_of(token: str) -> Set[str]:
    global _SYN_MAP
    if _SYN_MAP is None:
        _SYN_MAP = build_synonym_map()
    t = (token or "").lower().strip().replace("_", " ").split()[0] if token else ""
    if not t:
        return set()
    return _SYN_MAP.get(t, {t})
